apiVersion: apps/v1
kind: Deployment
metadata:
  name: curlserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curlserver
  template:
    metadata:
      labels:
        app: curlserver
    spec:
      containers:
      - name: curlserver
        image: gcr.io/google_containers/echoserver:1.9
        # imagePullPolicy: Always
        name: curlserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: curlserverservice
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: curlserver