apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: default
  labels: 
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.19.2
        ports:
        - containerPort: 16686 # UI
        - containerPort: 5778 # serve configs, sampling strategies
        - containerPort: 6831 # accept jaeger.thrift in compact Thrift protocol used by most current Jaeger clients
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: default
spec:
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686
      name: jaeger-ui-port
    - protocol: TCP
      port: 5778
      targetPort: 5778
      name: jaeger-sampling-server
    - protocol: TCP
      port: 6831
      targetPort: 6831
      name: jaeger-local-agent-address